apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::421530794463:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-s5iLLwbCscFS
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::421530794463:user/anitha
      username: anitha    
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-06T02:05:11Z"
  name: aws-auth
  namespace: kube-system
  uid: d10ff25e-d967-4ef1-a9d0-22fc849cb8ac